name: Bump Version

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Enter the commit SHA'
        type: string
        required: true
      version_fragment:
        description: 'Choose the bump type'
        required: true
        default: 'bug'
        options: ['major', 'feature', 'bug', 'alpha', 'beta', 'pre', 'rc']
        type: choice

jobs:
  bump-version:
    # Only on default branch
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_sha }}
          fetch-depth: '0'

      # WyriHaximus' project is buggy atm (18.04.2023)
      - name: Get Previous tag
        id: previous_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          # Optional fallback tag to use when no tag can be found
          fallback: 0.0.0
          prefix: v

      # Probably an alternative
      #  - uses: oprypin/find-latest-tag@v1
      #    id: previous_tag
      #    with:
      #      repository: Zeratoxx/Drag-n-Compress
      #      prefix: v

      - name: 'Bump version in "${{ github.event.inputs.version_fragment }}" step'
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: ${{ steps.previous_tag.outputs.tag }}
          version-fragment: ${{ github.event.inputs.version_fragment }}

      - name: "Version bump from '${{ steps.previous_tag.outputs.tag }}' to '${{ steps.bump_version.outputs.next-version }}'"
        run: echo "Version bump from '${{ steps.previous_tag.outputs.tag }}' to '${{ steps.bump_version.outputs.next-version }}'"

      - name: Push tag
        id: push_tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ github.event.inputs.commit_sha }}
          custom_tag: ${{ steps.bump_version.outputs.next-version }}
          create_annotated_tag: true
