name: bundle
on:
  workflow_call:
    inputs:
      version:
        description: 'Version of the bundle'
        required: true
        type: string

jobs:
  create-win-bundle:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so job can access repo files
      - uses: actions/checkout@v3

      - name: Download and unzip FFmpeg
        run: |
          wget https://github.com/GyanD/codexffmpeg/releases/download/5.1.2/ffmpeg-5.1.2-full_build.zip
          unzip ffmpeg-5.1.2-full_build.zip
       
      - name: Create bundle dir
        run: |
          mkdir win-bundle
          mv ./ffmpeg-5.1.2-full_build/bin/ffmpeg.exe ./win-bundle/
          mv ./ffmpeg-5.1.2-full_build/bin/ffprobe.exe ./win-bundle/
          mv ./LICENSE ./win-bundle/
          mv ./README.md ./win-bundle/
          mv ./*.ps1 ./win-bundle/
       
      - name: Create zip with compression  
        run: zip -9 -r win-bundle_${{ inputs.version }} ./win-bundle/
        
      - name: Upload zip as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.version }}win-bundle
          path: win-bundle_${{ inputs.version }}.zip
          retention-days: 2
