name: Latest

on:
  # Triggers the workflow on push events on the default branch
  push:
    branches:
      - ${{ github.event.repository.default_branch }}
  workflow_dispatch:

jobs:
  create-dev-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Set variable for dev version
        run: |
          echo "DEV_VERSION=0.0.0" >> $GITHUB_ENV

      - name: Push tag
        id: push_tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN_ZERATOXX }}
          custom_tag: ${{ env.DEV_VERSION }}
          tag_prefix: v
          create_annotated_tag: true