name: Dev release on latest commit of default branch

on:
  # Triggers the workflow on push events on the default branch
  workflow_dispatch:
  push:

env:
  DEV_VERSION: v0.0.0

jobs:
  cleanup-of-dev-release:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    outputs:
      dev-version: ${{ env.DEV_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Delete Release and Tag
        run: gh release delete ${{ env.DEV_VERSION }} --cleanup-tag
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-dev-release-based-on-current-default-branch:
    needs: cleanup-of-dev-release
    uses: ./.github/workflows/publish-release.yml
    with:
      version: ${{ needs.cleanup-of-dev-release.outputs.dev-version }}
