name: Dev release on latest commit of default branch

on:
  # Triggers the workflow on push events on the default branch
  workflow_dispatch:
  push:

env:
  DEV_VERSION: v0.0.0

jobs:
  cleanup-of-dev-release:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    outputs:
      dev-version: ${{ env.DEV_VERSION }}
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v1.0 # PRERELEASE is v1.0 and can also be used to test and give us feedback
        with:
          tag_name: ${{ env.DEV_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true

  create-dev-release-based-on-current-default-branch:
    needs: cleanup-of-dev-release
    uses: ./.github/workflows/publish-release.yml
    with:
      tag: ${{ needs.cleanup-of-dev-release.outputs.dev-version }}
