name: Latest

on:
  # Triggers the workflow on push events on the default branch
  workflow_dispatch:
  push:

jobs:
  get-repo-information:
    runs-on: ubuntu-22.04
    steps:
      - name: Get information
        run: |
          echo "Default branch is: ${{ github.event.repository.default_branch }}"
          echo "ref is: ${{ github.ref }}"
          echo "ref_name is: ${{ github.ref_name }}"
          echo "event ref is: ${{ github.event.ref }}"
          echo "event ref_name is: ${{ github.event.ref_name }}"

  create-dev-release:
    if: github.event.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-22.04
    steps:
      - name: Set variable for dev version
        run: |
          echo "DEV_VERSION=0.0.0" >> $GITHUB_ENV

      - name: Push tag
        id: push_tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN_ZERATOXX }}
          custom_tag: ${{ env.DEV_VERSION }}
          tag_prefix: v
          create_annotated_tag: true