name: Publish release

on:
  create:
  push:
    tags:
      - "*"

jobs:
  bundle:
    if: github.ref_type == 'tag'
    name: Bundle version ${{ github.ref_name }}
    uses: ./.github/workflows/bundle.yml
    with:
      version: ${{ github.ref_name }}

  publish-release:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-22.04
    needs: bundle
    name: Publish release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download bundle artifact
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.bundle.outputs.artifact-path }}

      - name: Publish release
        uses: eloquent/github-release-action@v3
        with:
          reactions: eyes,hooray,rocket
          assets: |
            - name: ${{ needs.bundle.outputs.artifact-path }}.zip
              path: ${{ steps.download-artifact.outputs.download-path }}/${{ needs.bundle.outputs.artifact-path }}.zip
