name: Publish release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  bundle:
    if: github.ref_type == 'tag'
    name: Bundle version ${{ github.ref_name }}
    uses: ./.github/workflows/bundle.yml
    with:
      version: ${{ github.ref_name }}

  publish-release:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-22.04
    needs: bundle
    name: Publish release
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download bundle artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.bundle.outputs.artifact-path }}

      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
        with:
          reactions: eyes,hooray,rocket
          assets: |
            - name: ${{ needs.bundle.outputs.artifact-path }}.zip
              path: ${{ steps.download-artifact.outputs.download-path }}/${{ needs.bundle.outputs.artifact-path }}.zip
              label: Bundled ZIP file with FFmpeg binaries included
