name: Publish release

on:
  create:
  push:
    tags:
      - "*"

jobs:
  bundle:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-22.04
    name: Bundle
    outputs:
      artifact-path: ${{ steps.bundle.outputs.artifact-path }}
    steps:
      - name: Bundle version ${{ github.ref_name }}
        id: bundle
        uses: ./.github/workflows/bundle.yml
        with:
          version: ${{ github.ref_name }}

  publish-release:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-22.04
    needs: bundle
    name: Publish release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download bundle artifact
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.bundle.outputs.artifact-path }}

      - name: Publish release
        uses: eloquent/github-release-action@v3
        with:
          reactions: hooray, rocket, eyes
          assets: |
            - path: ${{ steps.download-artifact.outputs.download-path }}
