name: Pull request bundle

on:

  # Triggers the workflow on events of pull requests with the default branch as the target
  pull_request:
    branches:
      - ${{ github.event.repository.default_branch }}
    with:
      version: "snapshot-${{ github.ref_name }}"

jobs:
  bundle:
    runs-on: ubuntu-22.04
    steps:
      - name: Bundle snapshot
        uses: ./.github/workflows/bundle.yml
        with:
          version: ${{ inputs.version }}
          retention-days: 8
