name: Pull request bundle

on:
  # Triggers the workflow on events of pull requests with the default branch as the target
  pull_request:
    branches:
      - ${{ github.event.repository.default_branch }}

jobs:
  bundle:
    runs-on: ubuntu-22.04
    steps:
      - name: Set variable for pull request version
        run: |
          echo "PR_VERSION=snapshot-${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Bundle snapshot
        uses: ./.github/workflows/bundle.yml
        with:
          version: ${{ env.PR_VERSION }}
          retention-days: 8
